//
// C8yAccessToken.swift
// CumulocityCoreLibrary
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
// Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.
//

import Foundation

/// OAI-Secure access token.
public struct C8yAccessToken: Codable {

	/// Access token generated by the Cumulocity IoT platform.
	public var accessToken: String?

	enum CodingKeys: String, CodingKey {
		case accessToken = "access_token"
	}

	public init() {
	}
}
